export 'package:app_plataforma/src/features/notificacion/presentation/pages/main_recommendations_screen.dart';
export 'package:app_plataforma/src/features/direccion/presentation/pages/direccion_screen.dart';
export 'package:app_plataforma/src/features/paciente/presentation/password/pages/update_password_screen.dart';
export 'package:app_plataforma/src/features/paciente/presentation/paciente/widgets/about_screen.dart';
export 'package:app_plataforma/src/features/notificacion/presentation/pages/personal_recommendations_screen.dart';
export 'package:app_plataforma/src/features/notificacion/presentation/pages/general_recommendations_screen.dart';
export 'package:app_plataforma/src/features/paciente/presentation/paciente/my_data/pages/mydata_screen.dart';
export 'package:app_plataforma/src/features/paciente/presentation/paciente/my_data/widgets/doctor_data.dart';
export 'package:app_plataforma/src/features/paciente/presentation/paciente/my_data/widgets/paciente_data.dart';