export 'package:app_plataforma/src/features/paciente/presentation/paciente/my_data/pages/doctor_data.dart';
export 'package:app_plataforma/src/features/paciente/presentation/paciente/my_data/pages/main_mydata_screen.dart';
export 'package:app_plataforma/src/features/paciente/presentation/paciente/my_data/pages/paciente_data.dart';
export 'package:app_plataforma/src/features/notificacion/presentation/pages/main_recommendations_screen.dart';
export 'package:app_plataforma/src/features/direccion/presentation/pages/direccion_screen.dart';
export 'package:app_plataforma/src/features/paciente/presentation/password/pages/update_password_screen.dart';
export 'package:app_plataforma/src/features/paciente/presentation/profile/pages/about_screen.dart';
export 'package:app_plataforma/src/features/notificacion/presentation/pages/personal_recommendations_screen.dart';
export 'package:app_plataforma/src/features/notificacion/presentation/pages/general_recommendations_screen.dart';
